name: Meu Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compliando no Java
        run: |
          cd src
          javac -cp . classTest.java Main.java

      - name: Rodando o progrma
        run: |
          cd src
          java -cp . classTest
          

