name: Meu Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build do projeto
        run: mvn clean package

      - name: Executar testes
        run: mvn test

      - name: Executar teste específico
        run: java -cp target/classes com.example.ClassTeste
